name: Günlük Portföy Raporu

on:
  schedule:
    # Her gün saat 13:00 UTC (Türkiye için +3 saat düşün)
    - cron: '0 10 * * 1-5'  # hafta içi
  workflow_dispatch:  # manuel çalıştırma için

jobs:
  run_portfoy:
    runs-on: ubuntu-latest

    steps:
    - name: Repoyu checkout et
      uses: actions/checkout@v3

    - name: Python kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Gereksinimleri yükle
      run: |
        python -m pip install --upgrade pip
        pip install yfinance pandas requests beautifulsoup4 matplotlib

    - name: Portföy raporunu çalıştır ve mail gönder
      run: python portfoy.py
      env:
        SMTP_USER: ${{ secrets.SMTP_USER }}
        SMTP_PASS: ${{ secrets.SMTP_PASS }}
        SMTP_TO: ${{ secrets.SMTP_TO }}
